name: mywb1
channels:
  - defaults
dependencies:
  - pip
  - anyio
  - python=3.12.12    
  - pip:
      - jupyterlab
      - notebook
      - mcp==1.20.0
      - fastmcp==2.13.0.2
      - fastapi==0.121.0
      - uvicorn==0.38.0
      - httpx[http2]==0.28.1
      - httpx-sse==0.4.3
      - pydantic==2.12.4
      - python-multipart==0.0.20
      - jinja2==3.1.6
      - langchain-ollama==1.0.0
      - ollama==0.6.0
      - python-dotenv==1.2.1
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - pandas==2.3.3
      - openpyxl==3.1.5
      - xlsxwriter==3.2.9
      - langchain==1.0.3
      - langchain-chroma==1.0.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.0.3
      - langgraph==1.0.2
      - langgraph-prebuilt==1.0.2
      - langgraph-sdk==0.2.9
      - langchain-text-splitters==1.0.0
      - langgraph-checkpoint==3.0.1
      - langchain-mcp-adapters==0.1.12
      - chromadb==1.3.4
      - pdfplumber==0.11.7
      - python-docx==1.2.0
      - pypdf==6.1.3
      - pypdfium2==5.0.0
      - reportlab==4.4.4
      - langchain-openai
      - litellm
      - google-adk
